name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest --html=report.html --self-contained-html

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_DEPLOY_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/my-python-app || git clone https://github.com/BFSIGENAI/ref_demo_cicd.git ~/my-python-app
          cd ~/my-python-app
          git pull origin main
          pip3 install -r requirements.txt
          
          # Example: restart Gunicorn service
          pkill gunicorn || true
          nohup gunicorn --bind 0.0.0.0:8000 app:app > app.log 2>&1 &
        EOF
