name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]   # change branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_DEPLOY_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/my-python-app || git clone https://github.com/BFSIGENAI/ref_demo_cicd.git ~/my-python-app
          cd ~/my-python-app
          git pull origin main
          pip3 install -r requirements.txt
          
          # Example: restart Gunicorn service
          pkill gunicorn || true
          nohup gunicorn --bind 0.0.0.0:8000 app:app > app.log 2>&1 &
        EOF
